// <auto-generated />
namespace Distributor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _42nd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_42nd));
        
        string IMigrationMetadata.Id
        {
            get { return "201709111559395_42nd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
