// <auto-generated />
namespace Distributor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _21th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21th));
        
        string IMigrationMetadata.Id
        {
            get { return "201708251037362_21th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
