// <auto-generated />
namespace Distributor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _43rd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_43rd));
        
        string IMigrationMetadata.Id
        {
            get { return "201709120725514_43rd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
